### ISSUE TITLE
Support for Redmine 4.x

### ISSUE THREAD

**Issue by christianlupus** [HugoHasenbein/redmine_auto_resubmission#1]
I tried to install the plugin in redmine 4.0. The reason is simply that I had to change my infrastructure and went to docker. Unfortunately, the 4.x version of redmine does not work well with the auto_resubmission plugin.
I use the plugin heavily and would like to see it usable in future releases as well.

Is there a chance/plan to make it compatible?

Just for reference, here is the relevant output from redmine:

```
redmine_1  | NoMethodError: undefined method `alias_method_chain' for ApplicationHelper:Module
redmine_1  | Did you mean?  alias_method
redmine_1  | /usr/src/redmine/plugins/redmine_auto_resubmission/lib/redmine_auto_resubmission/patches/application_helper_patch.rb:31:in `block in included'
redmine_1  | /usr/src/redmine/plugins/redmine_auto_resubmission/lib/redmine_auto_resubmission/patches/application_helper_patch.rb:28:in `class_eval'
redmine_1  | /usr/src/redmine/plugins/redmine_auto_resubmission/lib/redmine_auto_resubmission/patches/application_helper_patch.rb:28:in `included'
redmine_1  | /usr/src/redmine/plugins/redmine_auto_resubmission/lib/redmine_auto_resubmission/patches/application_helper_patch.rb:73:in `include'
redmine_1  | /usr/src/redmine/plugins/redmine_auto_resubmission/lib/redmine_auto_resubmission/patches/application_helper_patch.rb:73:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
redmine_1  | /usr/src/redmine/plugins/redmine_auto_resubmission/lib/redmine_auto_resubmission.rb:29:in `block in <top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
redmine_1  | /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
redmine_1  | /usr/src/redmine/config/environment.rb:14:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
redmine_1  | /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
redmine_1  | Tasks: TOP => db:migrate => db:load_config => environment
redmine_1  | (See full trace by running task with --trace)
```

**Comment by christianlupus** [comment]
@HugoHasenbein Is there any chance that the plugin gets ported to redmine 4.x?

Unfortunately, I am no ruby developer. Thus, I cannot be much of help here, sorry.

**Comment by HugoHasenbein** [comment]
1.0.5 release on github supports redmine 4+

**Comment by christianlupus** [comment]
Perfect. Thank you for your quick support. That seems to work in a test environment! I'll close the issue.
